@echo off
echo 🚀 Preparando projeto para GitHub...

:: Criar diretório do projeto
mkdir camerata21-platform
cd camerata21-platform

:: Copiar arquivos principais
echo 📁 Copiando arquivos...
copy "..\Code.gs.final" "Code.gs"
copy "..\index.html" "frontend\"
copy "..\frontend\cadastro.html" "frontend\"
copy "..\frontend\admin.html" "frontend\"
copy "..\_redirects" "site_camerata21\"
copy "..\README.md" "."
copy "..\DEPLOY_GUIDE.md" "docs\"

:: Criar estrutura do GitHub
echo 🏗️ Criando estrutura do GitHub...

:: .gitignore
echo. > .gitignore
echo # Node modules >> .gitignore
echo node_modules/ >> .gitignore
echo # Dependencies >> .gitignore
echo /node >> .gitignore
echo # Build outputs >> .gitignore
echo /build >> .gitignore
echo # Logs >> .gitignore
echo npm-debug.log* >> .gitignore
echo yarn-debug.log* >> .gitignore
echo yarn-error.log* >> .gitignore
echo # Runtime data >> .gitignore
echo pids >> .gitignore
echo *.pid >> .gitignore
echo *.seed >> .gitignore
echo *.pid.lock >> .gitignore
echo # Directory for instrumented libs generated by jscoverage/JSCover >> .gitignore
echo lib-cov >> .gitignore
echo # Coverage directory used by tools like istanbul >> .gitignore
echo coverage >> .gitignore
echo # nyc test coverage >> .gitignore
echo .nyc_output >> .gitignore
echo # Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files) >> .gitignore
echo .grunt >> .gitignore
echo # Bower dependency directory (https://bower.io/) >> .gitignore
echo bower_components >> .gitignore
echo # node-waf configuration >> .gitignore
echo .lock-wscript >> .gitignore
echo # Compiled binary addons (https://nodejs.org/api/addons.html) >> .gitignore
echo build/Release >> .gitignore
echo # Dependency directories >> .gitignore
echo jspm_packages/ >> .gitignore
echo # TypeScript v1 declaration files >> .gitignore
echo typings/ >> .gitignore
echo # Optional npm cache directory >> .gitignore
echo .npm >> .gitignore
echo # Optional eslint cache >> .gitignore
echo .eslintcache >> .gitignore
echo # Optional REPL history >> .gitignore
echo .node_repl_history >> .gitignore
echo # Output of 'npm pack' >> .gitignore
echo *.tgz >> .gitignore
echo # Yarn Integrity file >> .gitignore
echo .yarn-integrity >> .gitignore
echo # dotenv environment variables file >> .gitignore
echo .env >> .gitignore
echo # parcel-bundler cache (https://parceljs.org/) >> .gitignore
echo .cache >> .gitignore
echo # Next.js build output >> .gitignore
echo .next >> .gitignore
echo # Nuxt.js build / generate output >> .gitignore
echo .nuxt >> .gitignore
echo # Gatsby files >> .gitignore
echo # https://www.gatsbyjs.org/docs/how-to/preventing-builds-upon-change-in-data-files/ >> .gitignore
echo .cache/ >> .gitignore
echo # Comment in the public line in if your project uses Gatsby and not Next.js >> .gitignore
echo # https://nextjs.org/blog/next-9-1 >> .gitignore
echo # next.js build output >> .gitignore
echo public >> .gitignore
echo # vuepress build output >> .gitignore
echo .vuepress/dist >> .gitignore
echo # Serverless directories >> .gitignore
echo .serverless >> .gitignore
echo # FuseBox cache >> .gitignore
echo .fusebox/ >> .gitignore
echo # DynamoDB Local files >> .gitignore
echo .dynamodb/ >> .gitignore
echo # TernJS port file >> .gitignore
echo .tern-port >> .gitignore
echo # Stores VSCode versions used for testing VSCode extensions >> .gitignore
echo .vscode-test >> .gitignore
echo # IDE files >> .gitignore
echo .vscode/ >> .gitignore
echo .idea/ >> .gitignore
echo *.swp >> .gitignore
echo *.swo >> .gitignore
echo *~ >> .gitignore
echo # OS files >> .gitignore
echo .DS_Store >> .gitignore
echo Thumbs.db >> .gitignore
echo # Logs >> .gitignore
echo logs >> .gitignore
echo *.log >> .gitignore
echo # Testing >> .gitignore
echo # coverage directory >> .gitignore
echo coverage/ >> .gitignore
echo # nyc test coverage >> .gitignore
echo .nyc_output >> .gitignore
echo # Temporary folders >> .gitignore
echo tmp/ >> .gitignore
echo temp/ >> .gitignore
echo # Google Apps Script specific >> .gitignore
echo .clasp.json >> .gitignore
echo .clasp.json >> .gitignore

:: .gitattributes
echo. > .gitattributes
echo *.js text eol=lf >> .gitattributes
echo *.html text eol=lf >> .gitattributes
echo *.css text eol=lf >> .gitattributes
echo *.md text eol=lf >> .gitattributes

:: Inicializar repositório Git
echo 🔄 Inicializando repositório Git...
git init
git add .
git commit -m "Initial commit: Camerata 21 platform v1.0

- Platforma de inscrição para Camerata 21
- Dashboard administrativo com OTP
- Design responsivo mobile-first
- Sistema de logística integrado
- E-mails personalizados com identidade visual

Co-Authored-By: Claude <noreply@anthropic.com>"

echo ✅ Pronto para push no GitHub!
echo.
echo 📝 Próximos passos:
echo 1. Crie um repositório no GitHub: https://github.com/new
echo 2. Execute: git remote add origin [URL_DO_SEU_REPOSITORIO]
echo 3. Execute: git push -u origin main
echo 4. Configure o GitHub Pages: Settings > Pages > Source > GitHub Actions
echo.
echo 🚀 O projeto está pronto para deploy!

pause